### ISSUE TITLE
Have the values of `local_neural_points` been modified between being selected from and reassigned to global neural points?

### ISSUE THREAD

**Issue by kevintsq** [PRBonn/PIN_SLAM#17]
Thanks for your great work! I have the following question:

In `NeuralPoints.reset_neural_points()`, `local_neural_points` are selected from global neural points:
```python
self.local_neural_points = self.neural_points[local_mask]
```
In `NeuralPoints.assign_local_to_global()`, `local_neural_points` are reassigned to global neural points:
```python
self.neural_points[local_mask] = self.local_neural_points
```
But after searching all the usages of `local_neural_points`, I cannot see whether their values are modified anywhere in the code. In other words, do`self.neural_points[local_mask]` remain the same values after the `NeuralPoints.assign_local_to_global()` operation?

Thanks for your time and explanation.

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work and your kind words.

Indeed, only the neural point features, certainty and timestamp are being updated during the map optimization for each frame. The coordinates and orientations of the neural points are not changing. They are only changing after loop correction and the change is conducted for the global map instead of the local map.

Therefore, the following two lines can be commented out:
```
# self.neural_points[local_mask[:-1]] = self.local_neural_points
# self.point_orientations[local_mask[:-1]] = self.local_point_orientations
```

Thanks for pointing it out. I will update the code later.

**Comment by kevintsq** [comment]
Thanks!
