### ISSUE TITLE
Error IndexError: too many indices for tensor of dimension 0

### ISSUE THREAD

**Issue by jiang-junlong** [PRBonn/PIN_SLAM#31]
When I run the PIN_SLAM on the SubT_MRS, it stops with the following error:
```
Traceback (most recent call last):  
  File "pin_slam.py", line 466, in <module>  
    run_pin_slam()  
  File "pin_slam.py", line 222, in run_pin_slam  
    neural_points.reset_local_map(local_map_pose[:3,3], None, local_map_frame_id, False, config.loop_local_map_time_window)  
  File "/home/uav/myproject/PIN_SLAM-main/model/neural_points.py", line 429, in reset_local_map  
    local_mask_idx = time_mask_idx[dist_mask]  # True index  
IndexError: too many indices for tensor of dimension 0
```
After I increased the _loop_local_map_time_window_ from 100 to 1000, the **RMSE increased**. I am wondering why this happens. Additionally, I turned on **o3d_vis_on = True** to visualize the process and it does not seem to be drifting.
And this is the DataSet link:[SubT_MRS](https://superodometry.com/iccv23_challenge_LiI#download)                
Thank you!

**Comment by jiang-junlong** [comment]
And this is the DataSet link:[](https://superodometry.com/iccv23_challenge_LiI#download)
[https://drive.google.com/drive/folders/1hHCsnc-gANmK6Oox-Im3hqRwsGGaJIuJ](url)

**Comment by YuePanEdward** [comment]
Hi, I remember that one needs to preprocess this dataset to extract the Velodyne point cloud. Can you maybe provide me with a subset of the preprocessed data (in `*.ply` or in `*.rosbag` with `sensor_msgs/PointCloud2` type topic? 

Besides, `loop_local_map_time_window` would only affect the loop closure detection. Is the increased RMSE caused by a missed detection of loop closure?

**Comment by jiang-junlong** [comment]
Thank you, I convert the velodyne_msgs/VelodyneScan data type to Pointcloud2 by the rosbag velodyne and rosbag rocord.And I use my python convert.py to read the rosbag and extract *.ply.

**Comment by jiang-junlong** [comment]
Tomorrow I will test the code again,thank you for your reply.

**Comment by jiang-junlong** [comment]
> Is the increased RMSE caused by a missed detection of loop closure?

I think it is.

**Comment by jiang-junlong** [comment]
> provide me with a subset of the preprocessed data (in `*.ply` or in `*.rosbag` with `sensor_msgs/PointCloud2` type topic?

链接: https://pan.baidu.com/s/1OEWVFJBV63UcwIslxhgfVg?pwd=9nnq 提取码: 9nnq 
--来自百度网盘超级会员v5的分享     This is my converted sequence dataset.

**Comment by YuePanEdward** [comment]
Could you please upload the data to Google drive? My Baidu drive account has expired.

**Comment by jiang-junlong** [comment]
> Could you please upload the data to Google drive? My Baidu drive account has expired.
I have uploaded it.Thank you very much.
https://drive.google.com/file/d/1gnXRpK_AEUOGWWTMCX87PSR9fVmg-yBg/view?usp=drive_link

**Comment by YuePanEdward** [comment]
Thanks for sending me the data. 

The bug seems to be because the local map time mask might be all False when the robot stops at a position for a long time and there's no new neural points being added. I will update the code to cope with such a situation. In such a case, it would be better to use the difference of accumulated travel distance to determine the temporal local map for loop closure context description. 

Currently, PIN-SLAM does not have a keyframe scheme. Therefore, it may have some redundancy during loop detection and pose graph optimization for long-term robot missions with a long time of stopping. I will update this keyframe scheme later if I have time. PRs on keyframes are also welcomed.

**Comment by jiang-junlong** [comment]
Thank you very much!
I understand why it happend
