### ISSUE TITLE
Unexpected artifacts when only perform mapping with gt pose.

### ISSUE THREAD

**Issue by marrblue** [PRBonn/PIN_SLAM#4]
Hi @YuePanEdward Thanks for your great work and making it open source!

I have met a strange problem when I run the mapping process on KITTI seq07 with tracking module disabled.
I straightforward use groundtruth poses for mapping and use  `run_kitti.yaml` as config file.
Then I noticed that the reconstruction of this region is not satisfactory when using ground truth poses, but if I use the full SLAM system with tracking, this region is nicely reconstructed.
![image](https://github.com/PRBonn/PIN_SLAM/assets/31070287/5e27abb5-9954-41c3-855d-e317a3696b39)
![image](https://github.com/PRBonn/PIN_SLAM/assets/31070287/2a4e0523-e1b1-4838-bd4d-31f59fc2f6e9)

This problem is kind of wired. I would appreciate it if you could provide some advice and hints on how to figure it out.
One potential reason is the car stopped here for a while, so I haved tried to remove these duplicated frames but it seems not helps.

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work.
I didn't notice this issue before and thanks for pointing it out.
After inspecting the data, I found out this issue could be mainly due to the unsmooth "groundtruth" poses of the KITTI dataset.

![issue4](https://github.com/PRBonn/PIN_SLAM/assets/34207278/f6edb4f9-2267-4ec1-8af8-8678003c3579)

As you can see in the above figure, the red trajectory is the one estimated by PIN-SLAM and the black trajectory is the "ground truth" GNSS-INS pose provided by KITTI. There's a jump on the Z-axis for the black trajectory. A similar situation can be found at the beginning of KITTI sequence 08. In some other sequences, you can clearly see there is some inconsistency in the trajectory at a revisited region on the Z-axis.

I suspect this unsmooth "groundtruth" poses is the cause of the unexpected artifacts. With the smooth pose estimated by PIN-SLAM, the artifacts would not appear and most of the dynamic objects can be removed by the free space sampling via raycasting.

I hope this help to answer your concern.
